# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: game.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\x12\x04game\"2\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"1\n\rLoginResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t*I\n\x07MsgType\x12\x0f\n\x0bMSG_UNKNOWN\x10\x00\x12\x15\n\x11MSG_LOGIN_REQUEST\x10\x01\x12\x16\n\x12MSG_LOGIN_RESPONSE\x10\x02\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MSGTYPE._serialized_start=123
  _MSGTYPE._serialized_end=196
  _LOGINREQUEST._serialized_start=20
  _LOGINREQUEST._serialized_end=70
  _LOGINRESPONSE._serialized_start=72
  _LOGINRESPONSE._serialized_end=121
# @@protoc_insertion_point(module_scope)
